# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://baka-san.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Grant Backes # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines
  # Header and footer text
  header_text: >
     <h1>Witty & Hilarious Rails Developer</h1>
     <p>Educator, science enthusiast, and developer specializing in Rails, JavaScript, and AngularJS.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: gsbackes@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket: baka-san  # bitbucket profile name, e.g. "madebymunsters"
  dribbble:
  facebook:
  flickr:
  github: baka-san # github profile name, e.g. "madebymunsters"
  google_plus:
  instagram:
  linkedin: www.linkedin.com/in/grant-backes # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: https://stackexchange.com/users/6979844/bakasan # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-109157548-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
